### PR TITLE
Set Minimum CPUs to 1 for each

### PR DESCRIPTION
**Pull request by AayushRd7**

### CODE REVIEW

**Comment by darshan1205** [comment]
:\ Random Reboots

**Comment by AayushRd7** [comment]
@darshan1205  Really? -_-

**Comment by karthick111** [comment]
lol

**Comment by faizauthar12** [comment]
i though we only able to set the main little or big cluster
(cpu0 and cpu4)
also it's using a paramters at rootdir (init)
min and max cpu , am i correct?

**Comment by karthick111** [comment]
yes

**Comment by AayushRd7** [comment]
Then fix there ;_;

**Comment by karthick111** [comment]
fix what ?

**Pull request closed without merging**
